name: ci
on: [push, pull_request]
permissions: {contents: read}
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1e60f620b9541dca151540d0c40b52c1b87e887e # v4.0.3
        with: {node-version: '20.19.6'}
      - run: npm test
      - run: npm run build
